# Generated by Django 2.0.6 on 2018-06-19 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sisautomacaosistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SisAutomacaoSistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sisclassificacaojuridica',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'SisClassificacaoJuridica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sisfiscalcstcofins',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'SisFiscalCSTCOFINS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sisfiscalcsticms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'SisFiscalCSTICMS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sisfiscalcstpis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'SisFiscalCSTPIS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sislogsistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('loja_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
                ('classe', models.CharField(max_length=60)),
                ('execucao', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'SisLogSistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sismenuprincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
                ('filho_id', models.IntegerField()),
                ('imagemnome', models.CharField(db_column='imagemNome', max_length=60)),
                ('tabpane', models.IntegerField(db_column='tabPane')),
                ('teclasatalho', models.CharField(db_column='teclasAtalho', max_length=45)),
            ],
            options={
                'db_table': 'SisMenuPrincipal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sismunicipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80)),
                ('iscapital', models.IntegerField(db_column='isCapital')),
                ('ibge_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sisMunicipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sisnfecfop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(max_length=350)),
                ('indnfe', models.IntegerField(db_column='indNFe')),
            ],
            options={
                'db_table': 'SisNFeCFOP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sisnfewebservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.IntegerField()),
                ('tipwebservice', models.CharField(db_column='tipWebService', max_length=30)),
                ('versaodados', models.CharField(db_column='versaoDados', max_length=10)),
                ('enderecowebservice', models.CharField(db_column='enderecoWebService', max_length=150)),
            ],
            options={
                'db_table': 'SisNFeWebServices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sisoperadorastelefonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'SisOperadorasTelefonia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sissefazamtributos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'SisSefazAMTributos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sissituacaosistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('classificacao', models.IntegerField()),
            ],
            options={
                'db_table': 'sisSituacaoSistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistabelaorigem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'sisTabelaOrigem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistipoendereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'sisTipoEndereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistipossaidadeprodutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SisTiposSaidaDeProdutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistipowebhomeemail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'SisTipoWebHomeEmail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sisuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('sigla', models.CharField(max_length=2)),
                ('ibge_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sisUF',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sisunidadescomercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'SisUnidadesComercial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabcargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tabCargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabcolaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('apelido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=80)),
                ('senha', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tabColaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabcontatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
                ('origemcodigo_id', models.IntegerField(db_column='origemCodigo_id')),
            ],
            options={
                'db_table': 'tabContatos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabempresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('ie', models.CharField(max_length=12)),
                ('razao', models.CharField(max_length=80)),
                ('fantasia', models.CharField(max_length=80)),
                ('iscliente', models.IntegerField(db_column='isCliente')),
                ('isfornecedor', models.IntegerField(db_column='isFornecedor')),
                ('istransportadora', models.IntegerField(db_column='isTransportadora')),
                ('datacadastro', models.DateTimeField(db_column='dataCadastro')),
                ('usuarioatualizacao_id', models.IntegerField(blank=True, db_column='usuarioAtualizacao_id', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='dataAtualizacao', null=True)),
                ('dataabertura', models.DateTimeField(blank=True, db_column='dataAbertura', null=True)),
                ('naturezajuridica', models.CharField(blank=True, db_column='naturezaJuridica', max_length=120, null=True)),
            ],
            options={
                'db_table': 'tabEmpresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabempresascondicoesprodutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id', models.IntegerField()),
                ('qtdminima', models.IntegerField(db_column='qtdMinima')),
                ('qtdbonificacao', models.IntegerField(db_column='qtdBonificacao')),
                ('vlrdesc', models.FloatField(db_column='vlrDesc')),
                ('prazo', models.IntegerField()),
            ],
            options={
                'db_table': 'tabEmpresasCondicoesProdutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabempresasprazos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensalista', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('limite', models.FloatField()),
                ('nfe', models.IntegerField()),
                ('recibo', models.IntegerField()),
            ],
            options={
                'db_table': 'tabEmpresasPrazos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabendereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=80)),
                ('bairro', models.CharField(max_length=40)),
                ('isativo', models.IntegerField(db_column='isAtivo')),
                ('codigoorigem_id', models.IntegerField(db_column='codigoOrigem_id')),
            ],
            options={
                'db_table': 'tabEndereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabestoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id', models.IntegerField()),
                ('qtd', models.IntegerField()),
                ('lote', models.CharField(max_length=20)),
                ('validade', models.DateTimeField()),
                ('vlrbruto', models.FloatField(db_column='vlrBruto')),
                ('vlrimposto', models.FloatField(db_column='vlrImposto')),
                ('vlrfretebruto', models.FloatField(db_column='vlrFreteBruto')),
                ('vlrimpostofrete', models.FloatField(db_column='vlrImpostoFrete')),
                ('vlrimpostodentrofrete', models.FloatField(db_column='vlrImpostoDentroFrete')),
                ('vlrfreteliquido', models.FloatField(db_column='vlrFreteLiquido')),
                ('vlrliquido', models.FloatField(db_column='vlrLiquido')),
                ('usuariocadastro_id', models.IntegerField(db_column='usuarioCadastro_id')),
                ('datacadastro', models.DateTimeField(db_column='dataCadastro')),
                ('documentoentrada', models.CharField(db_column='documentoEntrada', max_length=20)),
                ('documentoentradachavenfe', models.CharField(db_column='documentoEntradaChaveNfe', max_length=44)),
            ],
            options={
                'db_table': 'tabEstoque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabloja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('ie', models.CharField(max_length=12)),
                ('isativa', models.IntegerField(db_column='isAtiva')),
                ('razao', models.CharField(max_length=80)),
                ('fantasia', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'tabLoja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabprodutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=120)),
                ('peso', models.FloatField()),
                ('precodefabrica', models.FloatField(db_column='precoDeFabrica')),
                ('margem', models.FloatField()),
                ('precodevenda', models.FloatField(db_column='precoDeVenda')),
                ('varejo', models.IntegerField()),
                ('comissao', models.FloatField()),
                ('nfencm', models.CharField(db_column='nfeNcm', max_length=8)),
                ('nfecest', models.CharField(db_column='nfeCest', max_length=8)),
                ('nfeorigem', models.IntegerField(db_column='nfeOrigem')),
                ('nfegenero', models.CharField(db_column='nfeGenero', max_length=10)),
                ('usuariocadastro_id', models.IntegerField(db_column='usuarioCadastro_id')),
                ('datacadastro', models.DateTimeField(db_column='dataCadastro')),
                ('usuarioatualizacao_id', models.IntegerField(blank=True, db_column='usuarioAtualizacao_id', null=True)),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='dataAtualizacao', null=True)),
            ],
            options={
                'db_table': 'tabProdutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabprodutosean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoean', models.CharField(db_column='codigoEan', max_length=13)),
            ],
            options={
                'db_table': 'tabProdutosEan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabsaidadeprodutositenstemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id', models.IntegerField()),
                ('produto_codigo', models.CharField(max_length=15)),
                ('produto_descricao', models.CharField(max_length=120)),
                ('estoque_id', models.IntegerField()),
                ('qtd', models.IntegerField()),
                ('produto_precodevenda', models.FloatField(db_column='produto_precoDeVenda')),
                ('descporcentagem', models.FloatField(db_column='descPorcentagem')),
                ('descvalor', models.FloatField(db_column='descValor')),
                ('vlrtotalbruto', models.FloatField(db_column='vlrTotalBruto')),
                ('vlrtotalliquido', models.FloatField(db_column='vlrTotalLiquido')),
                ('estoque_qtd', models.IntegerField()),
                ('estoque_validade', models.DateTimeField()),
                ('estoque_lote', models.CharField(max_length=20)),
                ('produto_varejo', models.IntegerField()),
                ('produto_volume', models.IntegerField()),
            ],
            options={
                'db_table': 'tabSaidaDeProdutosItensTemp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabsaidadeprodutostemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcamento', models.IntegerField()),
                ('data', models.DateTimeField()),
            ],
            options={
                'db_table': 'tabSaidaDeProdutosTemp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabtelefones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=11)),
                ('origemcodigo_id', models.IntegerField(db_column='origemCodigo_id')),
            ],
            options={
                'db_table': 'tabTelefones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabwebhomeemail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80)),
                ('origemcodigo_id', models.IntegerField(db_column='origemCodigo_id')),
            ],
            options={
                'db_table': 'tabWebHomeEmail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabempresasdetalhesreceitafederal',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cafeperfeito.Tabempresas')),
                ('empresa_id', models.IntegerField()),
                ('descricao', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tabEmpresasDetalhesReceitaFederal',
                'managed': False,
            },
        ),
    ]
